version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-sportstore
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sport_store_A4C10
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: sportstore-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sport_store_A4C10?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      